# Generated by Django 5.1.4 on 2024-12-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_books_readers_alter_books_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
