# Generated by Django 5.1.4 on 2024-12-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_books_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='rating',
        ),
    ]
