# Generated by Django 5.1.4 on 2024-12-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_books_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
